# This file is for use with Docker!
# This is a compose file for development! Do not use in prod!
# This file needs the backend to be started first!

services:
  jhaas-portal-frontend:
    image: jhaas-portal-frontend
    container_name: jhaas-portal-frontend
    hostname: jhaas-portal-frontend
    restart: unless-stopped
    build:
      context: .
      target: develop
    networks:
      - jhaas-portal-priv
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - cache:${CACHEDIR:-/jhaas-cache}
      - ./:${APPDIR:-/jhaas-app}
      - ./docker-entrypoint-dev.sh:/entrypoint.sh:ro

networks:
  jhaas-portal-priv:
    external: true
    name: jhaas-portal-priv

volumes:
  cache:
    name: jhaas-portal-frontend-cache
