##########################################################
# CAUTION
# This Dockerfile can only be used within the CI pipeline,
# as it depends on artifacts from preceding jobs.
##########################################################
FROM node:18 AS build

ARG APPDIR=/jhaas-app
WORKDIR ${APPDIR}

COPY . .

# node_modules are coming from ci artifact
RUN npm run build

FROM nginx:1.23-alpine AS production

ARG APPDIR=/jhaas-app

COPY --from=build ${APPDIR}/dist /usr/share/nginx/html
